server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: postgres://plivhiiqemfdad:cccaa9842d33e6988605ffeb108a9ccf6caae711ffc77385b5282feee5a4dfe5@ec2-52-4-111-46.compute-1.amazonaws.com:5432/dadtl92cel9hcu
    #username: postgres
    username: plivhiiqemfdad
    #password: 123456
    password: cccaa9842d33e6988605ffeb108a9ccf6caae711ffc77385b5282feee5a4dfe5
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para TESTE 