server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/postgres
    url: postgres://gxicaibdjnvizw:f64a10df017c1fd056d576edb7cf6cfb19ed4a3c574ca2b3528f7d952dc5646b@ec2-34-195-143-54.compute-1.amazonaws.com:5432/d440av20is6eok
    #username: postgres
    username: gxicaibdjnvizw
    #password: 123456
    password: f64a10df017c1fd056d576edb7cf6cfb19ed4a3c574ca2b3528f7d952dc5646b
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander