server:
  port: 8080
  servlet:
    context-path: /appsantander

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://zmdbecnozzhisy:c32a6c7045b6035be211fd97ec0759936c3fa106fb847a3d265b80ae2d605011@ec2-3-234-22-132.compute-1.amazonaws.com:5432/ddku5n8em0nc25
    username: zmdbecnozzhisy
    password: c32a6c7045b6035be211fd97ec0759936c3fa106fb847a3d265b80ae2d605011
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none

application:
  description: Project created for DIO bootcamp - Santander dev Week
  version: 1.0
